/* rangeplay_keys.h: input event key codes (RP_IN_CODE of RP_EV_KEY_DOWN / RP_EV_KEY_UP), generated from KEY_CODES in
 * src/shared/layout.js by tools/gen-keys.js. Do not edit. 0 means a key without a code here. */
#ifndef RANGEPLAY_KEYS_H
#define RANGEPLAY_KEYS_H

#define RP_KEY_KeyA 1
#define RP_KEY_KeyB 2
#define RP_KEY_KeyC 3
#define RP_KEY_KeyD 4
#define RP_KEY_KeyE 5
#define RP_KEY_KeyF 6
#define RP_KEY_KeyG 7
#define RP_KEY_KeyH 8
#define RP_KEY_KeyI 9
#define RP_KEY_KeyJ 10
#define RP_KEY_KeyK 11
#define RP_KEY_KeyL 12
#define RP_KEY_KeyM 13
#define RP_KEY_KeyN 14
#define RP_KEY_KeyO 15
#define RP_KEY_KeyP 16
#define RP_KEY_KeyQ 17
#define RP_KEY_KeyR 18
#define RP_KEY_KeyS 19
#define RP_KEY_KeyT 20
#define RP_KEY_KeyU 21
#define RP_KEY_KeyV 22
#define RP_KEY_KeyW 23
#define RP_KEY_KeyX 24
#define RP_KEY_KeyY 25
#define RP_KEY_KeyZ 26
#define RP_KEY_Digit0 27
#define RP_KEY_Digit1 28
#define RP_KEY_Digit2 29
#define RP_KEY_Digit3 30
#define RP_KEY_Digit4 31
#define RP_KEY_Digit5 32
#define RP_KEY_Digit6 33
#define RP_KEY_Digit7 34
#define RP_KEY_Digit8 35
#define RP_KEY_Digit9 36
#define RP_KEY_ArrowUp 37
#define RP_KEY_ArrowDown 38
#define RP_KEY_ArrowLeft 39
#define RP_KEY_ArrowRight 40
#define RP_KEY_Space 41
#define RP_KEY_Enter 42
#define RP_KEY_Escape 43
#define RP_KEY_Tab 44
#define RP_KEY_Backspace 45
#define RP_KEY_ShiftLeft 46
#define RP_KEY_ShiftRight 47
#define RP_KEY_ControlLeft 48
#define RP_KEY_ControlRight 49
#define RP_KEY_AltLeft 50
#define RP_KEY_AltRight 51
#define RP_KEY_MetaLeft 52
#define RP_KEY_MetaRight 53
#define RP_KEY_F1 54
#define RP_KEY_F2 55
#define RP_KEY_F3 56
#define RP_KEY_F4 57
#define RP_KEY_F5 58
#define RP_KEY_F6 59
#define RP_KEY_F7 60
#define RP_KEY_F8 61
#define RP_KEY_F9 62
#define RP_KEY_F10 63
#define RP_KEY_F11 64
#define RP_KEY_F12 65
#define RP_KEY_Minus 66
#define RP_KEY_Equal 67
#define RP_KEY_BracketLeft 68
#define RP_KEY_BracketRight 69
#define RP_KEY_Backslash 70
#define RP_KEY_Semicolon 71
#define RP_KEY_Quote 72
#define RP_KEY_Backquote 73
#define RP_KEY_Comma 74
#define RP_KEY_Period 75
#define RP_KEY_Slash 76
#define RP_KEY_CapsLock 77
#define RP_KEY_Insert 78
#define RP_KEY_Delete 79
#define RP_KEY_Home 80
#define RP_KEY_End 81
#define RP_KEY_PageUp 82
#define RP_KEY_PageDown 83
#define RP_KEY_Numpad0 84
#define RP_KEY_Numpad1 85
#define RP_KEY_Numpad2 86
#define RP_KEY_Numpad3 87
#define RP_KEY_Numpad4 88
#define RP_KEY_Numpad5 89
#define RP_KEY_Numpad6 90
#define RP_KEY_Numpad7 91
#define RP_KEY_Numpad8 92
#define RP_KEY_Numpad9 93
#define RP_KEY_NumpadAdd 94
#define RP_KEY_NumpadSubtract 95
#define RP_KEY_NumpadMultiply 96
#define RP_KEY_NumpadDivide 97
#define RP_KEY_NumpadDecimal 98
#define RP_KEY_NumpadEnter 99

#endif /* RANGEPLAY_KEYS_H */
